package controller;

public enum Action {
	SHOW_DIALOG_CREATE, EXIT, BUTTON_ADD_PRODUCT, CLOSE_DIALOG_CREATE_PRODUCT, BUTTON_SAVE_PRODUCT, BUTTON_EDIT_PRODUCT, BUTTON_REMOVE_PRODUCT,BUTTON_SEARCH_BY_NAME,BUTTON_SEARCH_BY_PRICE,BUTTON_SEARCH_BY_CATEGORY, BUTTON_PRODUCTOS, BUTTON_LAST_PAGE_BACK, BUTTON_PAGE_BACK, BUTTON_PAGE_NEXT, BUTTON_LAST_PAGE_NEXT, SHOW_DIALOG_SETTINGS, BUTTON_SAVE_SETTINGS, BUTTON_CANCEL_SETTINGS, BUTTON_SELECT_IMAGE, CANCEL_PATH, SAVE_PATH, BUTTON_CHOOSE_IMAGE_FOR_FILES, BUTTON_CHOOSE_IMAGE_FOR_FOLDERS, BUTTON_CLOSE_CHOOSER_FILES, BUTTON_FILTER, BUTTON_ALL, BUTTON_BIO_PRODUCT, CLOSE_DIALOG_BIO_PRODUCT, BUTTON_OPEN_DIALOG_ADMIN, BUTTON_OPEN_DIALOG_CUSTOMER, OPEN_DIALOG_DESCRIPTION_PRODUCT, CLOSE_DIALOG_DESCRIPTION_PRODUCT, BUTTON_SAVE_DESCRIPTION;
	
}
